name: First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6 
          
        - name: List Files
          run: ls

        - name: Execute Shell Script
          run: ./my-script.sh
          
          
